### ISSUE TITLE
Provider Support

### ISSUE THREAD

**Issue by Insomniak47** [wareismymind/peer#91]
We might want to wait until after we make some decisions about the AsyncEnumerable fetcher parts

- [ ] #92
  - [ ] Create AzDO Fetcher
  - [ ] Create AzDO Provider Config
  - [ ] Create AzDO Registration Handler
- [ ] #93
  - [ ] Create GitLab Provider Config
  - [ ] Create GitLab Fetcher
  - [ ] Create GitLab Registration Handler
- [ ] #94
  - [ ] Create BitBucket Provider Config
  - [ ] Create BitBucket Fetcher
  - [ ] Create BitBucket Registration Handler
